#!/usr/bin/env node
var moment = require('moment');
var request = require('request'); 
var mysql = require('mysql');

moment().format();

var monday = 'SELECT * FROM `time-table` WHERE thu=2';
var tuesday = 'SELECT * FROM `time-table` WHERE thu=3';
var wednesday= 'SELECT * FROM `time-table` WHERE thu=4';
var thursday= 'SELECT * FROM `time-table` WHERE thu=5';
var friday = 'SELECT * FROM `time-table` WHERE thu=6';
var saturday = 'SELECT * FROM `time-table` WHERE thu=7';
var sunday = 'SELECT * FROM `time-table` WHERE thu=CN';

alert_time = moment('16:00','h:mm');

var today = moment.weekdays(moment().day());
var queryString = ''
if(today == 'Monday')
    if (moment() < alert_time)
	queryString = monday
    else
	queryString = tuesday
else if(today == 'Tuesday')
    if (moment() < alert_time)
	queryString = tuesday
    else
	queryString = wednesday
else if(today == 'Wednesday')
    if (moment() < alert_time)
	queryString = wednesday
    else
	queryString = thursday
else if(today == 'Thursday')
    if (moment() < alert_time)
	queryString = thursday
    else
	queryString = friday
else if(today == 'Friday')
    if (moment() < alert_time)
	queryString = friday
    else
	queryString = saturday
else if(today == 'Saturday')
    if (moment() < alert_time)
	queryString = saturday
    else
	queryString = sunday
else
    if (moment() < alert_time)
	queryString = sunday
    else
	queryString = monday

function parseObj(obj){
    if(!obj.tiet1)
	obj.tiet1 = ''
    if(!obj.tiet2)
	obj.tiet2 = ''
    if(!obj.tiet3)
	obj.tiet3 = ''
    if(!obj.tiet4)
	obj.tiet4 = ''
    if(!obj.tiet5)
	obj.tiet5 = ''
    if(!obj.tiet6)
	obj.tiet6 = ''
    if(!obj.tiet7)
	obj.tiet7 = ''
    if(!obj.tiet8)
	obj.tiet8 = ''
    let _res = `
    ----------------------
    | Lich thu ${obj.thu}:
    | ${obj.tiet1}
    | ${obj.tiet2}
    | ${obj.tiet3}
    | ${obj.tiet4}
    ----------------------
    | ${obj.tiet5}
    | ${obj.tiet6}
    | ${obj.tiet7}
    | ${obj.tiet8}
    ----------------------
    `;  
    return _res;
}


function Talk(msg){
    request({
	url:
//	'https://hooks.slack.com/services/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',
	'https://slack.com/api/chat.postMessage',
	method : 'POST',
	headers: {
	    'Contain-type': 'application/json',
	    'Authorization': 'Bearer xoxb-880939714258-885480425185-dSLaCyVFiCVcs47iTVN5EQYE',

	    },
	    json: {
		token: 'xoxb-880939714258-885480425185-dSLaCyVFiCVcs47iTVN5EQYE',
		channel: 'learning',
		text: msg
	    }
	},function(error, res, body){
    });
}

var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'time-table'
});

connection.connect(function(err) {
   if (err) throw err;
   connection.query(queryString,function (err, result, field){
	if (err) throw err;
	res = parseObj(result[0]);
	Talk(res);
	console.log(res);
	connection.end();
   }); 
});

//something
